name: CI_Run_UB2104_Tests_QRDUMP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: ubuntu 21.10
    runs-on: ubuntu-latest
    container: ubuntu:21.10

    steps:
      - uses: actions/checkout@v2
      
      - name: run all tests including slow and UB2104
        run: |
          apt-get update
          apt-get install git -y
          apt-get install sudo -y
          cd src
          bash install.sh
          cd ../tests/
          bash run_all_tests.sh
          bash run_all_tests_UB2104.sh
